Resources:
  UserRegistrationServiceRoleBCB3F31D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkExampleStack/UserRegistration/ServiceRole/Resource
  UserRegistration1E985772:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43cS3Bucket3C706BA7
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43cS3VersionKey5C44FFA4
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43cS3VersionKey5C44FFA4
      Role:
        Fn::GetAtt:
          - UserRegistrationServiceRoleBCB3F31D
          - Arn
      FunctionName: UserRegistration
      Handler: index.UserRegistrationHanlder
      MemorySize: 1024
      Runtime: nodejs14.x
    DependsOn:
      - UserRegistrationServiceRoleBCB3F31D
    Metadata:
      aws:cdk:path: CdkExampleStack/UserRegistration/Resource
      aws:asset:path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserRegistration
      aws:asset:original-path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserRegistration
      aws:asset:is-bundled: false
      aws:asset:property: Code
  UserEmailConfirmServiceRole1A79C4F4:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkExampleStack/UserEmailConfirm/ServiceRole/Resource
  UserEmailConfirmB609801E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883S3Bucket6FE5D86D
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883S3VersionKey256A511A
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883S3VersionKey256A511A
      Role:
        Fn::GetAtt:
          - UserEmailConfirmServiceRole1A79C4F4
          - Arn
      Handler: index.handler
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 40
    DependsOn:
      - UserEmailConfirmServiceRole1A79C4F4
    Metadata:
      aws:cdk:path: CdkExampleStack/UserEmailConfirm/Resource
      aws:asset:path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserEmailConfirm
      aws:asset:original-path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserEmailConfirm
      aws:asset:is-bundled: false
      aws:asset:property: Code
  StateMachineRoleB840431D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - states.
                    - Ref: AWS::Region
                    - .amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: CdkExampleStack/StateMachine/Role/Resource
  StateMachineRoleDefaultPolicyDF1E6607:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - UserRegistration1E985772
                - Arn
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - UserEmailConfirmB609801E
                - Arn
        Version: "2012-10-17"
      PolicyName: StateMachineRoleDefaultPolicyDF1E6607
      Roles:
        - Ref: StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: CdkExampleStack/StateMachine/Role/DefaultPolicy/Resource
  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"User Registration","States":{"User Registration":{"Next":"User Email Confirm","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","OutputPath":"$.Payload","Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::lambda:invoke","Parameters":{"FunctionName":"
            - Fn::GetAtt:
                - UserRegistration1E985772
                - Arn
            - '","Payload.$":"$"}},"User Email Confirm":{"End":true,"Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","OutputPath":"$.Payload","Resource":"arn:'
            - Ref: AWS::Partition
            - :states:::lambda:invoke","Parameters":{"FunctionName":"
            - Fn::GetAtt:
                - UserEmailConfirmB609801E
                - Arn
            - '","Payload.$":"$"}}}}'
    DependsOn:
      - StateMachineRoleDefaultPolicyDF1E6607
      - StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: CdkExampleStack/StateMachine/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/11Q0UoDMRD8lr7ntsYTn7WFgqBQzi9Yc9ua5i6R7KYiIf/uJVUsPs0MOzvDroas+1u4WT3gJ3dmdGsTIkF+FTRObYNnicmI2h78HiPOJBSrGIhDioYqX1yjFRt8Ubq/u87KleQJ57cRIe+SN9VWd355URZnyEOYWlTDfZis+WqVjRXFfYfMJAyPFRYNm2QcyQaZFAt9HH7yuBNkx/DcOp/8Obh/hnab0Auad+tb6bUuRV0e0IqWydH6498fyjL3YSQ48fqs70H3oFcntraLyYudCYYLfgMgGOrZWAEAAA==
    Metadata:
      aws:cdk:path: CdkExampleStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43cS3Bucket3C706BA7:
    Type: String
    Description: S3 bucket for asset "2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43c"
  AssetParameters2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43cS3VersionKey5C44FFA4:
    Type: String
    Description: S3 key for asset version "2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43c"
  AssetParameters2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43cArtifactHashD64A2A82:
    Type: String
    Description: Artifact hash for asset "2997849becde32ad231964628b3a521052db06f444f23dccfcffcc93ee28a43c"
  AssetParameters7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883S3Bucket6FE5D86D:
    Type: String
    Description: S3 bucket for asset "7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883"
  AssetParameters7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883S3VersionKey256A511A:
    Type: String
    Description: S3 key for asset version "7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883"
  AssetParameters7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883ArtifactHash1202EDF8:
    Type: String
    Description: Artifact hash for asset "7345ab6d5cbad35c8b189a8f8503ed8a56c2f6e7f9dabd362663e239403d9883"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

