Resources:
  signUpCustomerServiceRole318FE6E1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: VrishkarServicesStack/signUpCustomer/ServiceRole/Resource
  signUpCustomer6EE06107:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0cS3BucketFD19767C
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0cS3VersionKey10CDF0AC
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0cS3VersionKey10CDF0AC
      Role:
        Fn::GetAtt:
          - signUpCustomerServiceRole318FE6E1
          - Arn
      Handler: index.UserRegistrationHanlder
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 40
    DependsOn:
      - signUpCustomerServiceRole318FE6E1
    Metadata:
      aws:cdk:path: VrishkarServicesStack/signUpCustomer/Resource
      aws:asset:path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserRegistration
      aws:asset:original-path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserRegistration
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/01Oyw7CIBD8lt7pVqzxrDXxbOoXrHRt6AMSFvRA+HdLG6Onmck8MhKirPewK0745lJ1Y6WsI4h3j2oUF2vYu6C8uDzNDR3O5Mll0RLb4BRlvqQ67bU1Scj68L8VM4kTzo8OIV6DUTmWO1+ehMYZYmundSpjElyXyEye4Zxh0dAENZJvkBd7e7hay81em/53NKUkjO0IBq5e8giyBlkMrHXpgvF6Jmg3/AAqGKwN+QAAAA==
    Metadata:
      aws:cdk:path: VrishkarServicesStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0cS3BucketFD19767C:
    Type: String
    Description: S3 bucket for asset "0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0c"
  AssetParameters0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0cS3VersionKey10CDF0AC:
    Type: String
    Description: S3 key for asset version "0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0c"
  AssetParameters0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0cArtifactHashFEAF0AD7:
    Type: String
    Description: Artifact hash for asset "0204bbc81823b4c5f88b9c49b9e2f36afbca2c53ee62a795d26623889ae60f0c"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

