Resources:
  UserRegistrationServiceRoleBCB3F31D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkExampleStack/UserRegistration/ServiceRole/Resource
  UserRegistration1E985772:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8S3BucketCCE49326
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8S3VersionKey629B0F22
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8S3VersionKey629B0F22
      Role:
        Fn::GetAtt:
          - UserRegistrationServiceRoleBCB3F31D
          - Arn
      FunctionName: UserRegistration
      Handler: index.UserRegistrationHanlder
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 15
    DependsOn:
      - UserRegistrationServiceRoleBCB3F31D
    Metadata:
      aws:cdk:path: CdkExampleStack/UserRegistration/Resource
      aws:asset:path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserRegistration
      aws:asset:original-path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserRegistration
      aws:asset:is-bundled: false
      aws:asset:property: Code
  UserEmailConfirmServiceRole1A79C4F4:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkExampleStack/UserEmailConfirm/ServiceRole/Resource
  UserEmailConfirmB609801E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dcS3BucketB445C7BA
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dcS3VersionKeyC6C7AD94
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dcS3VersionKeyC6C7AD94
      Role:
        Fn::GetAtt:
          - UserEmailConfirmServiceRole1A79C4F4
          - Arn
      FunctionName: userEmail
      Handler: index.handler
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 15
    DependsOn:
      - UserEmailConfirmServiceRole1A79C4F4
    Metadata:
      aws:cdk:path: CdkExampleStack/UserEmailConfirm/Resource
      aws:asset:path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserEmailConfirm
      aws:asset:original-path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\functions\UserEmailConfirm
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zVPyw7CMAz7lt27wDTEmYeEhMQBjS8IXYZKWYuaFA5V/511wMl2ZMdyA027gmW1wTfXureLpH0gSBdBbdWWmWSiN+Nuau8dS4ha1H5wZww4klAooiP2MWgqfHL1Rox3WZWX6YHjtUdIh+h0ORfPn2dlcITU+cccLZgVtzWWWoa5fdKwi9qS7JBJsdBz+MW5FmTLcJorju7lLeWsnO8J7rx4NetpHDTVnY2pQ3RiRoLuix9VfomO+AAAAA==
    Metadata:
      aws:cdk:path: CdkExampleStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8S3BucketCCE49326:
    Type: String
    Description: S3 bucket for asset "871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8"
  AssetParameters871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8S3VersionKey629B0F22:
    Type: String
    Description: S3 key for asset version "871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8"
  AssetParameters871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8ArtifactHash4F4844E7:
    Type: String
    Description: Artifact hash for asset "871d8a0e245ce0456380add64ddf79381625794913bfa6324bfb9306ecae22b8"
  AssetParameters3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dcS3BucketB445C7BA:
    Type: String
    Description: S3 bucket for asset "3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dc"
  AssetParameters3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dcS3VersionKeyC6C7AD94:
    Type: String
    Description: S3 key for asset version "3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dc"
  AssetParameters3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dcArtifactHashC6CA463A:
    Type: String
    Description: Artifact hash for asset "3440e629ea943f88c44eddd2b9a8117fff42e2da58be70283b92a8b6bc3936dc"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

