Resources:
  UserRegistrationServiceRoleBCB3F31D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkExampleStack/UserRegistration/ServiceRole/Resource
  UserRegistration1E985772:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797bS3BucketE08CABFC
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797bS3VersionKeyC7240C16
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797bS3VersionKeyC7240C16
      Role:
        Fn::GetAtt:
          - UserRegistrationServiceRoleBCB3F31D
          - Arn
      FunctionName: UserRegistration
      Handler: index.UserRegistrationHanlder
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 15
    DependsOn:
      - UserRegistrationServiceRoleBCB3F31D
    Metadata:
      aws:cdk:path: CdkExampleStack/UserRegistration/Resource
      aws:asset:path: /Users/ramya/Desktop/vrishkarprojects/vk-cleanerportal-ms/functions/UserRegistration
      aws:asset:original-path: /Users/ramya/Desktop/vrishkarprojects/vk-cleanerportal-ms/functions/UserRegistration
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zWNzQoCMQyEn8V7N1pWPPsDguBB1ieI3Si1bitNqofSd3e76mm+CTMZDbpdwmK2xjc3pnfzbEIkyGdB49SGmWTEm/U3tQueJSYjanf1J4w4kFCspiMOKRqqPKZ6Kzb4ourL/MDh0iPkffKmnmvmz0VZHCB34TFVqxbFbYN1lmFaHz1sk3EkW2RSLPS8/urcCLJjOE4TB/8KjkpRPvQEd56/9BL0CvTsztY2MXmxA0H31Q+vs7K7+AAAAA==
    Metadata:
      aws:cdk:path: CdkExampleStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersc393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797bS3BucketE08CABFC:
    Type: String
    Description: S3 bucket for asset "c393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797b"
  AssetParametersc393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797bS3VersionKeyC7240C16:
    Type: String
    Description: S3 key for asset version "c393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797b"
  AssetParametersc393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797bArtifactHashC7737E9D:
    Type: String
    Description: Artifact hash for asset "c393f72db6078f2a02bf0b6a79ec5cbacd960fda5947e8deac6b95a3103b797b"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

