Resources:
  signupServiceRole22DA917C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: VkCleanerportalMsStack/signup/ServiceRole/Resource
  signup3542BA4E:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6S3Bucket4754CF09
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6S3VersionKey772C7BF9
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6S3VersionKey772C7BF9
      Role:
        Fn::GetAtt:
          - signupServiceRole22DA917C
          - Arn
      FunctionName: signup
      Handler: index.handler
      MemorySize: 1024
      Runtime: nodejs14.x
    DependsOn:
      - signupServiceRole22DA917C
    Metadata:
      aws:cdk:path: VkCleanerportalMsStack/signup/Resource
      aws:asset:path: C:\Users\kiran\vrishkar\vk-cleanerportal-ms\function
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zWOwQ7CIBBEv6V3urVp9Kw18WzqF6ywNrQFEhb0QPh3ocbTvNnM7mwP/XCEQ3PGD7dSrV2SzhOkR0C5igszhYKztrO4OsvBRxnE9WXv6NFQIF/NROyil1S5pJQO2tks6sm0oXkqhHSLVtZxzfw5C40G0uS2fbVqFjy0WGsZ9vbiYYxypTAiU87COkWwcPfuT+V36JuFtW59tEEbgumnXwg13o7XAAAA
    Metadata:
      aws:cdk:path: VkCleanerportalMsStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6S3Bucket4754CF09:
    Type: String
    Description: S3 bucket for asset "160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6"
  AssetParameters160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6S3VersionKey772C7BF9:
    Type: String
    Description: S3 key for asset version "160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6"
  AssetParameters160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6ArtifactHash5751A808:
    Type: String
    Description: Artifact hash for asset "160912c2ec02c01e4cac81aaa236dcd6da233b9cfbb1835a66580ddd3e96c8b6"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

